#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Setup Aliases
if [[ -s "${ZDOTDIR:-$HOME}/.aliases" ]]; then
  source "${ZDOTDIR:-$HOME}/.aliases"
fi

# For now use .powerlin-shell.py (https://github.com/briandela/powerline-shell)
function powerline_precmd() {
  PS1="$(~/.powerline-shell.py $? --shell zsh 2> /dev/null)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

export NVM_DIR="/Users/brian/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

if [[ -s "${ZDOTDIR:-$HOME}/.dotfiles/zsh/modules/gulp/gulp.plugin.zsh" ]]; then
    source ${ZDOTDIR:-$HOME}/.dotfiles/zsh/modules/gulp/gulp.plugin.zsh
fi

# added by travis gem
[ -f /Users/brian/.travis/travis.sh ] && source /Users/brian/.travis/travis.sh

#aws cli auto complete
if [[ -s "/usr/local/bin/aws_zsh_completer.sh" ]]; then
  source /usr/local/bin/aws_zsh_completer.sh
fi

# kubectl
if  type "$kubectl" > /dev/null; then
    source <(kubectl completion zsh)
fi
