# Install NPM modules
npm install -g depcheck
npm install -g diff-so-fancy
npm install -g eslint
npm install -g json
npm install -g n
npm install -g np
npm install -g node-inspector
npm install -g npm-check-updates
npm install -g nsp
npm install -g pm2
npm install -g spoof
npm install -g surge
npm install -g trucker
